### ISSUE TITLE
Result seems incorrect

### ISSUE THREAD

**Issue by joe11chen** [yuweichuan/ECL-PF#2]
Dear ECL-PF team:

I used your software for non-cleavable data analysis. I saw "Output: E:/ECL-PF-main/XLpeplib_Beveridge_QEx-HFX_DSS_R1_final.csv" in the running log. However, I only found "XLpeplib_Beveridge_QEx-HFX_DSS_R1.csv" (without "_final" in filename). Then,I opend it, found decoyresults were not filtered. I am wondering what's going wrong?
![image](https://github.com/user-attachments/assets/0779c2e2-cd64-4e61-9782-826927115b30)

Best regards
Joe Chen

**Comment by yuweichuan** [comment]
Hi Joe,

I downloaded the data you were using and ran the ECL3. All the three replicates of the XLpeplib_Beveridge_QEx-HFX_DSS (R1, R2 and R3) were successfully analysed. Can you try to put the data file under the root directory of ECL-PF-main and try again running the ECL3 using the parameters below? Let's try if there is something wrong in the params setting part.

![data setting](https://github.com/user-attachments/assets/664e2b43-be63-4c1e-91cd-c6e06145b2e1)
![tool setting](https://github.com/user-attachments/assets/67194e0e-172b-45fe-b430-ae7e9c9126a9)
![final files](https://github.com/user-attachments/assets/0f40dbaa-80af-43ed-84ea-92c56e67ea8c)
![final results](https://github.com/user-attachments/assets/75f4c895-c1bf-4a63-9851-2e152296529f)

**Comment by joe11chen** [comment]
I’ve resolved the issue by switching my conda env. I previously installed the packages in a wrong environment. Thanks for your help!
